name: Rustls
on:
  workflow_dispatch:

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on:  ubuntu-latest
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on:  ubuntu-latest
            target: aarch64-unknown-linux-musl

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - uses: actions/checkout@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
      - name: Upload Artifacts sign
        uses: actions/upload-artifact@master
        with:
           name: bita-${{ matrix.platform.target }}
           target: target/${{ matrix.platform.target }}/release/bita